[pytest]
# Registering markers to remove warnings
markers =
    ui: User Interface tests using Playwright
    api: Backend API integration tests
    smoke: Critical path tests for quick verification

# Optional: Add default execution flags here too
addopts = --alluredir=allure-results -v